name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: fishmingyu
          template: classic
          base: ""
          repositories_affiliations: owner, collaborator, organization_member
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Leo Yu, fishmingyu, fishming
          plugin_languages_limit: 8
          plugin_languages_details: percentage, lines
          plugin_languages_ignored: html, css, makefile, cmake
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          config_timezone: America/Los_Angeles
          filename: metrics.svg
          output_action: commit
